# Generated by Django 3.1.1 on 2020-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('filesize', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(upload_to='videos/upload/')),
                ('file_score32', models.FileField(default='', upload_to='features/')),
                ('file_score64', models.FileField(default='', upload_to='features/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
