# Generated by Django 3.1.1 on 2020-10-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='row_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
