# Generated by Django 3.1.1 on 2020-10-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201026_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
